os:
  - linux

language: go
go:
  - 1.12
  - 1.13
go_import_path: github.com/ovh/utask

cache: apt

addons:
  postgresql: "9.5"

env:
  global:
  - GO111MODULE=on
  - DEV=true
  - PG_USER=travis
  - PG_PASSWORD=travispwd
  - PG_HOST=localhost
  - PG_PORT=5432
  - PG_DATABASENAME=travisdb
  - PSQL_BIN="psql travisdb"

before_script:
  - psql -c 'create database travisdb;' -U postgres

script:
  - make test-travis
  - make
  - make release

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - install-utask.sh
    - utask
  skip_cleanup: true
  draft: true
  on:
    tags: true

after_success:
  - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - curl -sL https://git.io/goreleaser | head -n -2 | bash
  - tar -xf /tmp/goreleaser.tar.gz -C $GOPATH/bin
  - git reset --hard HEAD  # reset go.mod and go.sum, modified by make test-travis, is this an OK move?
  - make run-goreleaser